### ISSUE TITLE
 GamifiveSDK.getConfig().user.level

### ISSUE THREAD

**Issue by servusdei** [D-Mobilelab/game-sdk#18]
I don't know if this is an issue or not, sorry if it's not the case.

But retrieving GamifiveSDK.getConfig().user.level always returns undefined. GamifiveSDK.endSession({ level: 1 }) doesn't seem to save the level.
GamifiveSDK.loadUserData and GamifiveSDK.saveUserData works fine so I'm using that to save and retrieve the level.

**Comment by eatsjobs** [comment]
@servusdei Hi. you can use a new function called GamfiveSDK.getLevel();
Please call both at the end of the session. We need the endSession for our leaderboards
var MycustomObject = {
/**... whatever **/
level:5
}
GamifiveSDK.saveUserData(MycustomObject)
GamifiveSDK.endSession({score:Number, level:Number})

**Comment by servusdei** [comment]
Yes, I suspected that you use that for a leader board, so I called it anyway.
Thank you.
