### ISSUE TITLE
Modifying hosts file is required before running npm run dev.

### ISSUE THREAD

**Issue by Trost123** [D-Mobilelab/game-sdk#24]
In the guide https://github.com/D-Mobilelab/game-sdk
"Edit your hosts file" goes after "Run the server", but actually you need to do it in reverse order.

**Comment by eatsjobs** [comment]
@Trost123 thanks for feedback. actually I'm rewriting the documentation just right now :)

**Comment by eatsjobs** [comment]
new doc preview https://github.com/D-Mobilelab/game-sdk/tree/develop
