### ISSUE TITLE
'more games' button reposition request

### ISSUE THREAD

**Issue by mentuat** [D-Mobilelab/game-sdk#27]
I can see there is/was a deprecated 'moreGamesButtonStyle' customise option.  What is the current method for re-positioning the 'more games' button to a different area?

The default position seems to be bottom right - exactly where the 'play' button is on various screens

**Comment by eatsjobs** [comment]
hi @mentuat the more games button is draggable. That's why it's not repositionable for now.

**Comment by eatsjobs** [comment]
@mentuat see the pull request #35

**Comment by eatsjobs** [comment]
Stable in version v2.6.1. Gonna close
